import { apiClient } from "./client";
export const fetchJobs = () => apiClient.get("/jobs/");
export const fetchJob = (jobId) => apiClient.get(`/jobs/${jobId}`);
export const fetchWorkers = () => apiClient.get("/workers/");
export const fetchJobRuns = (jobId) => apiClient.get(`/jobs/${jobId}/runs`);
export const fetchJobOverview = () => apiClient.get("/overview/jobs");
export const fetchQueueOverview = () => apiClient.get("/queue/overview");
export const fetchHistory = () => apiClient.get("/history/");
export const fetchJobGrid = (jobId) => apiClient.get(`/jobs/${jobId}/grid`);
export const fetchJobGantt = (jobId) => apiClient.get(`/jobs/${jobId}/gantt`);
export const fetchJobGraph = (jobId) => apiClient.get(`/jobs/${jobId}/graph`);
export const createJob = (payload) => apiClient.post("/jobs/", payload);
export const updateJob = (jobId, payload) => apiClient.put(`/jobs/${jobId}`, payload);
export const validateJob = (payload) => apiClient.post("/jobs/validate", payload);
export const validateJobById = (jobId) => apiClient.post(`/jobs/${jobId}/validate`, {});
export const runJobNow = (jobId) => apiClient.post(`/jobs/${jobId}/run`, {});
export const runAdhocJob = (payload) => apiClient.post("/jobs/adhoc", payload);
