imagePullPolicy: IfNotPresent
imagePullSecrets: []
demoMode:
  enabled: false
redis:
  enabled: true
  image:
    repository: redis
    tag: 7-alpine
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 500m
      memory: 256Mi
  persistence:
    enabled: true
    size: 2Gi
    storageClassName: ''
  nodeSelector: {}
  tolerations: []
  affinity: {}
mongodb:
  enabled: true
  image:
    repository: mongo
    tag: '6.0'
  database: hydra_jobs
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 1000m
      memory: 1Gi
  persistence:
    enabled: true
    size: 8Gi
    storageClassName: ''
  nodeSelector: {}
  tolerations: []
  affinity: {}
scheduler:
  enabled: true
  mode: combined
  replicas: 1
  image:
    repository: hydra-scheduler
    tag: 0.3.0
  service:
    type: ClusterIP
    port: 8000
  heartbeatTtl: 10
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi
  extraEnv: []
  nodeSelector: {}
  tolerations: []
  affinity: {}
orchestrator:
  replicas: 1
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi
  nodeSelector: {}
  tolerations: []
  affinity: {}
ui:
  enabled: true
  replicas: 1
  image:
    repository: hydra-ui
    tag: 0.3.0
  service:
    type: ClusterIP
    port: 80
  apiBaseUrl: ''
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 250m
      memory: 128Mi
  nodeSelector: {}
  tolerations: []
  affinity: {}
workers:
  - name: python-default
    flavor: python
    replicas: 2
    domain: prod
    tags: batch,data
    allowedUsers: ''
    maxConcurrency: 4
    workerState: online
    requireRedisAcl: true
    image:
      repository: hydra-worker
      tag: 0.3.0
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: '1'
        memory: 1Gi
    autoscaling:
      enabled: false
      minReplicas: 1
      maxReplicas: 10
      targetCPUUtilizationPercentage: 70
    nodeSelector: {}
    tolerations: []
    affinity: {}
  - name: go-lightweight
    flavor: go
    replicas: 2
    domain: prod
    tags: go,lightweight
    allowedUsers: ''
    maxConcurrency: 8
    workerState: online
    requireRedisAcl: true
    image:
      repository: hydra-go-worker
      tag: 0.3.0
    resources:
      requests:
        cpu: 50m
        memory: 64Mi
      limits:
        cpu: 500m
        memory: 256Mi
    autoscaling:
      enabled: false
      minReplicas: 1
      maxReplicas: 10
      targetCPUUtilizationPercentage: 70
    nodeSelector: {}
    tolerations: []
    affinity: {}
domainSeed:
  defaultDomain: prod
  extraDomains: []
  image:
    repository: hydra-scheduler
    tag: 0.3.0
ingress:
  enabled: false
  className: ''
  annotations: {}
  ui:
    host: hydra.local
    tls: []
  scheduler:
    host: hydra-api.local
    tls: []
commonLabels: {}
