import { jsxs as _jsxs, jsx as _jsx } from "react/jsx-runtime";
import { useParams, Link } from "react-router-dom";
import { useQuery } from "@tanstack/react-query";
import { Card, Descriptions, Space, Tag, Typography, List, Button } from "antd";
import { fetchWorkers } from "../api/jobs";
export function WorkerDetailPage() {
    const { workerId } = useParams();
    const { data, isLoading } = useQuery({ queryKey: ["workers"], queryFn: fetchWorkers, refetchInterval: 5000 });
    const worker = (data ?? []).find((w) => w.worker_id === workerId);
    return (_jsxs(Space, { direction: "vertical", size: "large", style: { width: "100%" }, children: [_jsxs(Typography.Title, { level: 3, style: { marginBottom: 0 }, children: ["Worker ", workerId] }), _jsx(Typography.Text, { type: "secondary", children: "Live metadata and current running jobs. Use the Workers page to change state or queues." }), _jsx(Button, { size: "small", children: _jsx(Link, { to: "/workers", children: "Back to Workers" }) }), _jsx(Card, { loading: isLoading || !worker, title: "Details", children: worker ? (_jsxs(Descriptions, { column: 1, bordered: true, size: "small", children: [_jsxs(Descriptions.Item, { label: "Status", children: [_jsx(Tag, { color: worker.status === "online" ? "green" : "volcano", children: worker.status }), " ", _jsx(Tag, { children: worker.state ?? "online" })] }), _jsx(Descriptions.Item, { label: "Host", children: worker.hostname }), _jsx(Descriptions.Item, { label: "IP", children: worker.ip }), _jsx(Descriptions.Item, { label: "OS", children: worker.os }), _jsx(Descriptions.Item, { label: "Deploy", children: worker.deployment_type }), _jsx(Descriptions.Item, { label: "Subnet", children: worker.subnet }), _jsx(Descriptions.Item, { label: "Queues", children: (worker.queues ?? ["default"]).join(", ") }), _jsx(Descriptions.Item, { label: "Tags", children: worker.tags.join(", ") || "-" }), _jsx(Descriptions.Item, { label: "Allowed Users", children: worker.allowed_users.join(", ") || "any" }), _jsxs(Descriptions.Item, { label: "Runtime", children: ["CPU ", worker.cpu_count ?? "-", " \u00B7 Python ", worker.python_version ?? "-", " \u00B7 User ", worker.run_user ?? "-"] }), _jsxs(Descriptions.Item, { label: "Concurrency", children: [worker.current_running, "/", worker.max_concurrency] }), _jsx(Descriptions.Item, { label: "Last Heartbeat", children: worker.last_heartbeat ? new Date(worker.last_heartbeat).toLocaleString() : "-" })] })) : (_jsx(Typography.Text, { children: "Worker not found." })) }), _jsx(Card, { title: "Running Jobs", children: _jsx(List, { loading: isLoading, dataSource: worker?.running_jobs ?? [], renderItem: (jobId) => (_jsx(List.Item, { children: _jsxs(Space, { children: [_jsx(Typography.Text, { children: "Job" }), _jsx(Link, { to: `/jobs/${jobId}`, children: jobId })] }) })) }) })] }));
}
