TEMPLATES = [
    {
        "id": "quick-shell",
        "name": "quick-shell",
        "user": "demo",
        "affinity": {"os": ["linux"], "tags": [], "allowed_users": []},
        "executor": {"type": "shell", "shell": "bash", "script": "echo quick-ok"},
        "retries": 0,
        "timeout": 30,
        "priority": 5,
        "schedule": {"mode": "immediate", "enabled": True},
        "completion": {
            "exit_codes": [0],
            "stdout_contains": ["quick-ok"],
            "stdout_not_contains": [],
            "stderr_contains": [],
            "stderr_not_contains": [],
        },
    },
    {
        "id": "long-sleep",
        "name": "long-sleep",
        "user": "demo",
        "affinity": {"os": ["linux"], "tags": [], "allowed_users": []},
        "executor": {"type": "shell", "shell": "bash", "script": "echo start; sleep 15; echo done"},
        "retries": 0,
        "timeout": 120,
        "priority": 4,
        "schedule": {"mode": "immediate", "enabled": True},
        "completion": {
            "exit_codes": [0],
            "stdout_contains": ["done"],
            "stdout_not_contains": ["error"],
            "stderr_contains": [],
            "stderr_not_contains": [],
        },
    },
    {
        "id": "python-env",
        "name": "python-env",
        "user": "demo",
        "affinity": {"os": ["linux"], "tags": ["python"], "allowed_users": []},
        "executor": {
            "type": "python",
            "interpreter": "python3",
            "code": "import sys; import platform; print('pyversion:', sys.version.split()[0]); print('platform:', platform.system())",
            "environment": {"type": "system", "python_version": "python3", "requirements": []},
        },
        "retries": 0,
        "timeout": 60,
        "priority": 5,
        "schedule": {"mode": "immediate", "enabled": True},
        "completion": {
            "exit_codes": [0],
            "stdout_contains": ["pyversion:"],
            "stdout_not_contains": [],
            "stderr_contains": [],
            "stderr_not_contains": [],
        },
    },
    {
        "id": "cron-ping",
        "name": "cron-ping",
        "user": "demo",
        "affinity": {"os": ["linux"], "tags": [], "allowed_users": []},
        "executor": {"type": "shell", "shell": "bash", "script": "echo cron-run $(date +%s)"},
        "retries": 0,
        "timeout": 30,
        "priority": 3,
        "schedule": {"mode": "cron", "cron": "*/5 * * * *", "enabled": True},
        "completion": {
            "exit_codes": [0],
            "stdout_contains": ["cron-run"],
            "stdout_not_contains": [],
            "stderr_contains": [],
            "stderr_not_contains": [],
        },
    },
    {
        "id": "test-echo",
        "name": "test-echo",
        "user": "rich",
        "affinity": {"os": ["linux"], "tags": [], "allowed_users": ["rich"]},
        "executor": {"type": "shell", "shell": "bash", "script": "echo 'hello world'"},
        "retries": 0,
        "timeout": 10,
        "priority": 5,
        "schedule": {"mode": "cron", "cron": "*/2 * * * *", "enabled": True},
        "completion": {
            "exit_codes": [0],
            "stdout_contains": ["hello"],
            "stdout_not_contains": [],
            "stderr_contains": [],
            "stderr_not_contains": [],
        },
    },
    {
        "id": "smoke-shell-quick",
        "name": "smoke-shell-quick",
        "user": "smoke",
        "affinity": {"os": ["linux"], "tags": [], "allowed_users": []},
        "executor": {"type": "shell", "shell": "bash", "script": "echo quick ok"},
        "retries": 0,
        "timeout": 30,
        "priority": 5,
        "schedule": {"mode": "immediate", "enabled": True},
        "completion": {
            "exit_codes": [0],
            "stdout_contains": [],
            "stdout_not_contains": [],
            "stderr_contains": [],
            "stderr_not_contains": [],
        },
    },
    {
        "id": "smoke-shell-long",
        "name": "smoke-shell-long",
        "user": "smoke",
        "affinity": {"os": ["linux"], "tags": [], "allowed_users": []},
        "executor": {"type": "shell", "shell": "bash", "script": "echo start; sleep 10; echo done"},
        "retries": 0,
        "timeout": 120,
        "priority": 4,
        "schedule": {"mode": "immediate", "enabled": True},
        "completion": {
            "exit_codes": [0],
            "stdout_contains": ["done"],
            "stdout_not_contains": [],
            "stderr_contains": [],
            "stderr_not_contains": [],
        },
    },
    {
        "id": "smoke-failing",
        "name": "smoke-failing",
        "user": "smoke",
        "affinity": {"os": ["linux"], "tags": [], "allowed_users": []},
        "executor": {"type": "shell", "shell": "bash", "script": "echo boom >&2; exit 42"},
        "retries": 0,
        "timeout": 30,
        "priority": 3,
        "schedule": {"mode": "immediate", "enabled": True},
        "completion": {
            "exit_codes": [0],
            "stdout_contains": [],
            "stdout_not_contains": [],
            "stderr_contains": [],
            "stderr_not_contains": [],
        },
    },
    {
        "id": "smoke-python",
        "name": "smoke-python",
        "user": "smoke",
        "affinity": {"os": ["linux"], "tags": ["python"], "allowed_users": []},
        "executor": {
            "type": "python",
            "interpreter": "python3",
            "code": "import time; print('tick'); time.sleep(2); print('tock')",
            "environment": {"type": "system", "python_version": "python3", "requirements": []},
        },
        "retries": 0,
        "timeout": 60,
        "priority": 5,
        "schedule": {"mode": "immediate", "enabled": True},
        "completion": {
            "exit_codes": [0],
            "stdout_contains": ["tock"],
            "stdout_not_contains": [],
            "stderr_contains": [],
            "stderr_not_contains": [],
        },
    },
    {
        "id": "smoke-cron",
        "name": "smoke-cron",
        "user": "smoke",
        "affinity": {"os": ["linux"], "tags": [], "allowed_users": []},
        "executor": {"type": "shell", "shell": "bash", "script": "echo cron-run $(date +%s)"},
        "retries": 0,
        "timeout": 30,
        "priority": 2,
        "schedule": {"mode": "cron", "cron": "*/5 * * * *", "enabled": True},
        "completion": {
            "exit_codes": [0],
            "stdout_contains": [],
            "stdout_not_contains": [],
            "stderr_contains": [],
            "stderr_not_contains": [],
        },
    },
]
